projectName: >-
  Implementing FIDO2 Passwordless Authentication: A Comprehensive Guide for
  <target_audience> Firms
jsonFilePath: ./input.json
baseUrl: ''
portalHeading: ''
portalDescription: ''
portalTitle: ''
searchPlaceholder: ''
useAlphabetsCategory: true
homeLink: ''
logoLink: ''
ctaText: ''
aboutLink: ''
productsLink: ''
logoImgUrl: ''
ctaLink: ''
copyrightText: ''
faviconUrl: ''
googleTagManagerId: ''
pagesTitle:
  prefix: ''
  suffix: ''
categoryPagesTitle:
  prefix: ''
  suffix: ''
templateRoot:
  - ./templates
  - ./templates
homeTemplatePath: ./templates/homePageTemplate.ejs
categoryTemplatePath: ./templates/categoryTemplate.ejs
pageTemplatePath: ./templates/pagesTemplate.ejs
outputDir: ./output
socialLinks: null
theme:
  primaryColor: '#3498db'
  secondaryColor: '#2ecc71'
  backgroundColor: '#ffffff'
  textColor: '#333333'
  accentColor: '#e74c3c'
fonts:
  - family: Roboto
    weights:
      - 400
      - 500
      - 600
  - family: Lato
    weights:
      - 500
      - 600
      - 700
